version: '2'

services:
    web:
        image: lavoweb/php-7.3
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./cache:/var/www/html/cache:Z
            - ./config/php.ini:/usr/local/etc/php/conf.d/90-php.ini
            - ./config/envvars:/etc/apache2/envvars
        links:
            - db:db
    db:
        image: mariadb:10.4.11-bionic
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
